Convert the text NULL data to the empty string before schema changes
Handling schema changes and data changes should be handled in separate
transactions to avoid pending trigger events.

Fixes the error:

django.db.utils.OperationalError: cannot ALTER TABLE "schedule_event" because it has pending trigger events

From:

https://docs.djangoproject.com/en/2.0/topics/migrations/#data-migrations

> Migrations that alter data are usually called “data migrations”;
> they’re best written as separate migrations, sitting alongside your
> schema migrations.

The previous data migration was implied by the alter operation.

Fixes #361